config/routes.rb
Rails.application.routes.draw do
  get 'abilities/new'
  get 'abilities/create'
  get 'reviews/new'
  devise_for :users
  root to: 'pages#home'

  resources :users do
    resources :beasts, only: [:new, :create]
  end

  resources :beasts, except: [:new] do
    resources :abilities, only: [:new, :create]
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, except: [:new, :create] do
   resources :reviews, only: [:new, :create]
  end

  # post "/beasts/:beast_id/bookings"  "bookings#create", as: :create_forum
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability < ApplicationRecord
  belongs_to :beast
  include PgSearch::Model
  multisearchable against: [:description]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beast.rb
class Beast < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:name, :category],
  using: {
      tsearch: { prefix: true }
  }

  has_one_attached :photo
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :abilities, dependent: :destroy
  has_many :reviews, through: :bookings

  validates :name, :category, :price, presence: true
  validates :dangerousness, presence: true, inclusion: {in: [1,2,3,4,5]}

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :beast

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :total_price, presence: true

  # has_one :user
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :content, presence: true
  validates :rating, presence: true, inclusion: {in: [1, 2, 3, 4, 5]}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include PgSearch::Model
  multisearchable against: [:email, :fullname]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :fullname, presence: true
  # validates :bio, presence: true

  has_many :bookings
  has_many :beasts
  has_one_attached :photo

end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
  def new
    @ability = Ability.new
    @beast = Beast.find(params[:beast_id])
  end

  def create
    @beast = Beast.find(params[:beast_id])
    @ability = Ability.new(ability_params)
    @ability.beast = @beast

    if @ability.save
      redirect_to beast_path(@beast)
    else
      render :new
    end
  end

  private
  def ability_params
    params.require(:ability).permit(:description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])

  end
end

app/controllers/beasts_controller.rb
class BeastsController < ApplicationController
  before_action :set_beast, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      @beasts_results = PgSearch.multisearch(params[:query])
    else
      @beasts = Beast.all
    end
  end

  def show
    @beast_geocoded = Beast.geocoded.find(params[:id])
    @marker = {
        lat: @beast_geocoded.latitude,
        lng: @beast_geocoded.longitude
      }
  end

  def new
    @beast = Beast.new
  end

  def create
    @beast = Beast.new(beast_params)
    @beast.user = current_user
    if @beast.save
      redirect_to beast_path(@beast)
    else
      render :new
    end
  end

  def edit; end

  def update
    @beast.update(beast_params)
    @beast.user = current_user
    if @beast.save
      redirect_to beast_path(@beast)
    else
      render :new
    end
  end

  def destroy
    @beast.destroy
    redirect_to beasts_path
  end

  private

  def set_beast
    @beast = Beast.find(params[:id])
  end

  def beast_params
    params.require(:beast).permit(:name, :category, :price, :location, :dangerousness, :photo)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]

  def index
    @bookings = current_user.bookings
  end

  def show; end

  def new
    @booking = Booking.new
    @beast = Beast.find(params[:beast_id])
  end

  def create
    @beast = Beast.find(params[:beast_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.beast = @beast

    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @booking.update(booking_params)
    @booking.user = current_user
    if @booking.save
      redirect_to beasts_path
    else
      render :new
    end
  end

  def destroy
    id = @booking.user_id
    @booking.destroy
    redirect_to user_path(id)
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @beasts = Beast.geocoded.all
    @markers = @beasts.map do |marker|
      {
        lat: marker.latitude,
        lng: marker.longitude
      }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @booking = Booking.find(params[:booking_id])
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking

    if @review.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  private
  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show; end

  # def new
  #   @user = User.new
  # end

  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     redirect_to user_path(@user)
  #   else
  #     render :new
  #   end
  # end

  def edit; end

  def update
    @user.update!(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :photo, :fullname, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/abilities/_ability_form.html.erb
<%= simple_form_for [@beast, @ability] do |f| %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/abilities/new.html.erb
<div class="content-container">

  <%= render partial: "ability_form" %>

</div>

app/views/beasts/_beast_form.html.erb
<%= simple_form_for @beast do |f| %>
  <%= f.input :name %>
  <%= f.input :category %>
  <%= f.input :dangerousness %>
  <%= f.input :price %>
  <%= f.input :location %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/beasts/edit.html.erb
<div class="content-container">
  <h1>Edit your beast</h1>
  <%= render partial: "beast_form" %>
</div>

app/views/beasts/index.html.erb
<div class="beast-container">

  <div class='row search-bar-container'>
    <%= form_tag beasts_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control search-input",
        placeholder: "Find a beast"
      %>
      <span class="input-group-btn">
        <i class="fas fa-search"><%= submit_tag "", class: "btn-dark search-btn" %></i>
      </span>
    <% end %>
  </div>

<!-- cards -->
  <div class="row justify-content-center">
    <% if @beasts_results.nil? %>
      <% @beasts.each do |beast| %>
        <div class="card col-12 col-md-5 col-lg-3 p-2 shadow-2 card-mobile" data-url="/beasts/<%= beast.id %>">

          <div class="card-img">
            <% if beast.photo.attached? %>
              <img class="card-img-top" src="<%= cl_image_path beast.photo.key, crop: :fill %>" alt="Card image cap">
            <% else %>
              <%= image_tag "koala-ava.png", alt: "Card image cap", class: "card-img-top"%>
            <% end %>
          </div>

          <div class="card-body shadow-text-2">
            <h3 class="card-title"><%= link_to beast.name, beast_path(beast) %></h3>
            <h6 class="card-text">Where to find: <%= beast.location %></h6>

          </div>

          <%= link_to 'More info', beast_path(beast),
              method: :get,
              class: 'btn btn-dark shadow-1' %>

        </div>
      <% end %>

    <% else %>

      <% @beasts_results.each do |beast| %>
        <% if beast.searchable_type == "Beast" %>
        <!-- another card -->
          <div class="card col-12 col-md-5 col-lg-3 p-2 shadow-2 card-mobile" data-url="/beasts/<%= beast.id %>">
            <div class="card-img">
              <% if beast.searchable.photo.attached? %>
                <img class="card-img-top" src="<%= cl_image_path beast.searchable.photo.key %>" alt="Card image cap">
              <% else %>
                <%= image_tag "koala-ava.png", alt: "Card image cap", class: "card-img-top"%>
              <% end %>
            </div>
            <div class="card-body shadow-text-2">
              <h3 class="card-title"><%= link_to beast.searchable.name, beast_path(beast.searchable) %></h3>
              <h6 class="card-text">Where to find: <%= beast.searchable.location %></h6>
            </div>
            <%= link_to 'More info', beast_path(beast.searchable),
                method: :get,
                class: 'btn btn-dark shadow-1' %>
          </div>
          <% end%>
      <% end %>
    <% end %>
  </div>
</div>


<script>
  let cards = document.querySelectorAll('.card');
  cards.forEach((el) => {
    el.classList.remove('rotate-ani');
    el.addEventListener('click', () => {
      el.classList.add('rotate-ani');
      redirect(el.getAttribute('data-url'));
  })})

  const redirect = (url) => {
    window.location.href = url;
  }
</script>

app/views/beasts/new.html.erb
<div class="content-container">
  <h1>Listing your beast</h1>
  <%= render partial: "beast_form" %>
</div>

app/views/beasts/show.html.erb
<div class="beast-container">
  <div class="first-row">
    <div class="card beast-img">
      <% if @beast.photo.attached? %>
          <%= cl_image_tag @beast.photo.key, class: 'img-fluid' %>
      <% else %>
        <%= image_tag "koala-ava.png", class: 'img-fluid' %>
      <% end %>
    </div>

    <div class="beast-info">
      <div class="title-container">
        <h1 class="card card-title shadow-text"><%= @beast.name %></h1>
        <% if @beast.reviews.exists? %>
          <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#exampleModalCenter">
            Read reviews
          </button>
        <% end %>
      </div>
      <div class="card card-info-body shadow-text-2">
        <h5 class="card-info-text"><%= @beast.category.capitalize %> Category</h5>
        <p class="card-info-text">Price per day: $<%= @beast.price %></p>
        <p class="card-info-text">Location: <%= @beast.location %></p>
        <p class="card-info-text">Danger level: <%= @beast.dangerousness %></p>

        <ul class="card-info-group">
          <h6>Abilities: </h6>
          <% @beast.abilities.each do |ability| %>
          <li><%= ability.description %> </li>
          <% end %>
        </ul>


      <!-- Need insert tag for reviews here -->


      </div>

      <div class="card card-btn-container">
        <%= link_to 'Home', beasts_path, class: 'btn btn-dark' %>
        <%= link_to 'Book now!', new_beast_booking_path(@beast), class: 'btn btn-dark' %>

        <% if @beast.user.id == current_user.id %>
          <%= link_to 'Add Ability to Beast', new_beast_ability_path(@beast), class: "btn btn-dark" %>
          <%= link_to 'Edit this beast', edit_beast_path(@beast),
            method: :get,
            class: 'btn btn-dark'  %>
          <%= link_to 'Delete', beast_path(@beast),
              method: :delete,
              data: {confirm: 'Are you sure deleting this beast?'}, class: 'btn btn-dark'  %>
        <% end %>
      </div>
    </div>
    </div>

    <!-- MapBox -->
    <div class="second-row">
      <div
          id="map"
          data-marker="<%= @marker.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        >
      </div>
    </div>

</div>



<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">All reviews</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="beast-reviews-container">
          <% @beast.reviews.each do |review| %>
          <li class="modal-review">
            <div>
              <div class="avatar" style="background: url(<%= cl_image_path review.booking.user.photo.key %>);"></div>
              <h6>from: <%= review.booking.user.email %></h6>
            </div>
            <h6><% (review.rating.to_i).times do %>
                <i class="fas fa-star"></i>
              <% end %>
            </h6>
            <p>"<%= review.content %>"</p>
          </li>
          <% end  %>
        </ul>
      </div>

    </div>
  </div>
</div>

app/views/bookings/_booking_form.html.erb
<%= simple_form_for [@beast, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.hidden_field :total_price %>
  <%= f.button :submit %>
<% end %>

app/views/bookings/edit.html.erb
<%= render partial: "booking_form" %>

app/views/bookings/index.html.erb
<div class='content-container'>
  <% @bookings.each do |booking| %>
  <div class='card-booking shadow-2'>
    <div class='bookings-avatar shadow-1'>
      <%= cl_image_tag booking.beast.photo.key %>
    </div>
    <div class='booking-text shadow-text-2'>
        <h5><%= link_to "#{booking.beast.name}", booking_path(booking)%></h5>
        <p>Start date: <%=booking.start_date %></p>
        <p>End date: <%=booking.end_date %></p>
        <p id='price'>Total: $<%=booking.total_price %></p>
    </div>
  </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="content-container">

  <h2>Booking form for <%= @beast.name %></h2>
  <h5>Total days: <span id='days_output'>0</span> -- Total price: <span id='price_output'>0</span> </h5>

  <%= render partial: "booking_form" %>

</div>

<script>
  const startDateInput = document.getElementById('booking_start_date_3i');
  const endDateInput = document.getElementById('booking_end_date_3i');
  const startMonthInput = document.getElementById('booking_start_date_2i');
  const endMonthInput = document.getElementById('booking_end_date_2i');
  const startYearInput = document.getElementById('booking_start_date_1i');
  const endYearInput = document.getElementById('booking_end_date_1i');
  const daysOutput = document.getElementById('days_output');
  const priceOutput = document.getElementById('price_output');
  const total = document.getElementById('booking_total_price');

  const inputs = [startDateInput, endDateInput, startMonthInput, endMonthInput, startYearInput, endYearInput];

  inputs.forEach(input => input.addEventListener('change', () => calculateDays()));

  const calculateDays = () => {
    let dateStart = new Date(`${startMonthInput.value}/${startDateInput.value}/${startYearInput.value}`);
    let dateEnd = new Date(`${endMonthInput.value}/${endDateInput.value}/${endYearInput.value}`);
    let Difference_In_Time = dateEnd.getTime() - dateStart.getTime();
    let Difference_In_Days = Math.floor(Difference_In_Time / (1000 * 3600 * 24));
    let totalPrice = <%= @beast.price %> * Difference_In_Days;

    daysOutput.innerText = Difference_In_Days;
    priceOutput.innerText = `$${totalPrice}`;
    total.setAttribute('value', totalPrice);
    console.log(total);
  }
</script>

app/views/bookings/show.html.erb
<div class="content-container">
  <div class="first-row">    
    <div class="card beast-img-booking">
      <% if @booking.beast.photo.attached? %>
          <%= cl_image_tag @booking.beast.photo.key, class: 'img-fluid' %>
      <% else %>
        <%= image_tag "koala-ava.png", class: 'img-fluid' %>
      <% end %>
    </div>      
    
    <div class="card card-btn-container">
        <%= link_to 'Home', beasts_path, class: 'btn btn-dark' %>
        <%= link_to 'Review', new_booking_review_path(@booking), class: 'btn btn-dark' %>
      </div>      
    <div class="reviews-container">
        <% @booking.reviews.each_with_index do |review, i| %>
          <div class=" card booking-info-container shadow-1">
            <h6><%= review.content %></h6>
            <h6><% (review.rating.to_i).times do %>
              <i class="fas fa-star"></i>
            <% end %>
            </h6>
            <p> Start date; <%= @booking.start_date %></p>
            <p> End date; <%= @booking.end_date %></p>
            <h6>Total price: $<%= @booking.total_price %></h6>
          </div>
        <% end %>
        </div>  
  
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Fantastic Beasts</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="content-container">
  <div class="banner-img"></div>

  <div class="banner">

    <div class="text-container">
      <h3>Your house's chores matter!</h3>
      <p>We're on a mission to revolutionize your ways to go through daily chores. So the Fantastic Beasts Renting concept was born. From lighting up a bbq fire to sweep through your dusty floor, there's nothing a mythical beast cannot do. Let rent a listed beast and let him do the chores for you.</p>
      <div id='extra-banner-text'><h5>How its works</h5>
        <p>- Go through our list of Fantastic Beasts -</p>
        <p>- Choose one with an ability that fits your goal -</p>
        <p>- Choose renting date and submit -</p>
        <p>- Finalize the payment and the beast will fly (or walk) to your house -</p>
      </div>
    </div>
    <%= link_to 'Start Now', beasts_path, class: 'btn  btn-banner' %>
     <div
          id="map2"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        >
  </div>
  </div>



</div>

app/views/reviews/_review_form.html.erb
<%= simple_form_for [@booking, @review] do |f| %>
  <%= f.input :content %>
  <div class="btn-container">
  <%= f.collection_radio_buttons :rating, [[1, '1'], [2, '2'], [3, '3'], [4, '4'] ,[5, '5']], :first, :last%>
  </div>
  <%= f.button :submit %>

<% end %>

app/views/reviews/new.html.erb
<div class="content-container">
  <h1>Reviews</h1>
  <%= render "review_form", class: 'form-review' %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag ( "https://res.cloudinary.com/dvbejvnhk/image/upload/v1582862507/logo-fantastic-beast_apl9ug.png" ) %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", beasts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "List your beast", new_user_beast_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/dvbejvnhk/image/upload/v1582693057/koala-ava_k6pdbq.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>

          <!-- avatar code here -->

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <%#= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/_user_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :fullname %>
  <%= f.input :bio %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

<div class="btn-container">
        <%= link_to 'Home', root_path, class: 'btn btn-light' %>
</div>

app/views/users/edit.html.erb
<div class="content-container">

<h1>Edit User</h1>
  <%= render partial: "user_form"%>

</div>

app/views/users/new.html.erb
<h1>Users#new</h1>


<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="page-show user" id='profile-container'>    <div class="profile-picture">
      <% if current_user.photo.attached? %>
        <%= cl_image_tag @user.photo.key, class: "card-img-top" %>
      <% else %>
        <%= image_tag "https://res.cloudinary.com/dvbejvnhk/image/upload/v1582693057/koala-ava_k6pdbq.png", class: "card-img-top" %>
      <% end %>
    </div>    
  <div class="card user shadow-2" id='user-info'>
      <div class="card-body shadow-text">
        <h2 class="card-title shadow-text"><%= @user.fullname %></h2>
        <h6 class="card-title">Email: <%= @user.email %></h6>
        <p class="card-text"><%= @user.bio %></p>
      </div>
      <div class="btn-container" id='profile-btn-container'>
        <%= link_to 'Home', root_path, class: 'btn btn-dark profile-home-btn  shadow-2' %>
        <%= link_to 'Edit this user', edit_user_path(@user),
            method: :get,
            class: 'btn btn-dark shadow-2'  %>
      </div>
    </div></div>